const allApis = {
  query: [
    // ==================== 哪吒 NZ 平台 ====================
    { id:'nz_8', name:'手机号二要素认证', desc:'运营商二要素检验，通过姓名+手机号进行信息比对，运营商数据库实时校验姓名和手机号码是否匹配。', price:0.93, method:'POST', endpoint:'/api/nz/8',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'phone',type:'string',required:true,desc:'手机号'}],
      responseParams:[{name:'code',type:'int',desc:'200=成功'},{name:'state',type:'string',desc:'1:一致; 2:不一致; 3:异常情况'},{name:'is_xhzw',type:'string',desc:'是否携号转网(0:否; 1:是)'},{name:'old_yys',type:'string',desc:'原运营商'},{name:'new_yys',type:'string',desc:'当前运营商'}],
      example:'{"name":"张三","phone":"13800138000"}', response:'{"code":200,"msg":"success","data":{"state":"2","is_xhzw":"0","old_yys":"移动","new_yys":"移动"}}' },

    { id:'nz_20', name:'全网手机号三要素验证', desc:'全网运营商三要素检验-手机号+姓名+证件号实名验证。', price:0.80, method:'POST', endpoint:'/api/nz/20',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'phone',type:'string',required:true,desc:'手机号'},{name:'idcard',type:'string',required:true,desc:'身份证号'}],
      responseParams:[{name:'state',type:'string',desc:'1:一致; 2:不一致; 3:异常情况'},{name:'is_xhzw',type:'string',desc:'是否携号转网'},{name:'old_yys',type:'string',desc:'原运营商'},{name:'new_yys',type:'string',desc:'当前运营商'}],
      example:'{"name":"张三","phone":"13800138000","idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"state":"2"}}' },

    { id:'nz_10', name:'IP归属地位置查询', desc:'IP定位解析，IP归属地位置查询。免费接口。', price:0, method:'POST', endpoint:'/api/nz/10',
      params:[{name:'ip',type:'string',required:true,desc:'IP地址'}],
      responseParams:[{name:'location',type:'string',desc:'归属地址'},{name:'Digitaladdress',type:'string',desc:'数字地址'},{name:'ip',type:'string',desc:'本次查询的IP'}],
      example:'{"ip":"27.38.248.215"}', response:'{"code":200,"msg":"success","data":{"location":"广东深圳龙华联通","ip":"27.38.248.215"}}' },

    { id:'nz_14', name:'身份证号码归属地查询', desc:'身份证号码归属地查询，返回性别、归属地、出生年月。', price:0.01, method:'POST', endpoint:'/api/nz/14',
      params:[{name:'idcard',type:'string',required:true,desc:'身份证号'}],
      responseParams:[{name:'sex',type:'string',desc:'性别'},{name:'area',type:'string',desc:'归属地'},{name:'birth',type:'string',desc:'出生年月'},{name:'status',type:'int',desc:'最后一位校验，0正确/1错误'}],
      example:'{"idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"sex":"男","area":"****","birth":"1998年07月10日","status":0}}' },

    { id:'nz_44', name:'限高消费人员查询', desc:'查询是否存在限制高消费的情况，返回案号、立案日期、关联对象等。', price:0.51, method:'POST', endpoint:'/api/nz/44',
      params:[{name:'name',type:'string',required:true,desc:'姓名或公司名'},{name:'idcard',type:'string',required:false,desc:'证件号或企业统代'}],
      responseParams:[{name:'status',type:'int',desc:'1=命中，2=未命中'},{name:'list',type:'array',desc:'限制高消费记录数组'}],
      example:'{"name":"张三"}', response:'{"code":200,"msg":"success","data":{"status":1,"list":[]}}' },

    { id:'nz_45', name:'失信被执行人员黑名单', desc:'查询全国失信被执行人老赖名单，包含企业和个人。', price:2.29, method:'POST', endpoint:'/api/nz/45',
      params:[{name:'name',type:'string',required:true,desc:'姓名或公司名'},{name:'idcard',type:'string',required:false,desc:'证件号或企业统代'}],
      responseParams:[{name:'status',type:'int',desc:'1=命中，2=未命中'},{name:'list',type:'array',desc:'失信记录数组'}],
      example:'{"name":"张三"}', response:'{"code":200,"msg":"success","data":{"status":1,"list":[]}}' },

    { id:'nz_40', name:'不良记录信息检验V2', desc:'对目标员工、用户进行曾经不良行为检验。', price:7.43, method:'POST', endpoint:'/api/nz/40',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'idcard',type:'string',required:true,desc:'身份证号'}],
      responseParams:[{name:'status',type:'int',desc:'1=命中，2=未命中'},{name:'status_msg',type:'string',desc:'结果文字说明'}],
      example:'{"name":"张三","idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"status":2,"status_msg":"查询成功无结果"}}' },

    { id:'nz_39', name:'人车实名检验-ETC', desc:'人车ETC关系检验，核验指定人员是否是指定车辆的所有人。', price:7.43, method:'POST', endpoint:'/api/nz/39',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'chepai',type:'string',required:true,desc:'车牌号'}],
      responseParams:[{name:'status',type:'int',desc:'1:一致; 2:不一致'}],
      example:'{"name":"张三","chepai":"京A12345"}', response:'{"code":200,"msg":"success","data":{"status":1}}' },

    { id:'nz_31', name:'人车实名检验', desc:'人车关系检验，核验指定人员是否是指定车辆的所有人。', price:17.14, method:'POST', endpoint:'/api/nz/31',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'chepai',type:'string',required:true,desc:'车牌号或VIN'}],
      responseParams:[{name:'state',type:'int',desc:'1:匹配; 2:不匹配'}],
      example:'{"name":"张三","chepai":"京A12345"}', response:'{"code":200,"msg":"success","data":{"state":1}}' },

    { id:'nz_41', name:'人车实名检验V2', desc:'人车关系检验V2。', price:10.29, method:'POST', endpoint:'/api/nz/41',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'chepai',type:'string',required:true,desc:'车牌号'}],
      responseParams:[{name:'state',type:'int',desc:'1:匹配;2:不匹配;3:查询成功无结果'}],
      example:'{"name":"张三","chepai":"京A12345"}', response:'{"code":200,"msg":"success","data":{"state":1}}' },

    { id:'nz_34', name:'车辆上险信息查询', desc:'根据车牌或vin车架号查询车辆交强险投保日期。', price:10.29, method:'POST', endpoint:'/api/nz/34',
      params:[{name:'value',type:'string',required:true,desc:'车牌号或VIN'}],
      responseParams:[{name:'old_date',type:'string',desc:'初次上险时间'},{name:'new_date',type:'string',desc:'最新上险时间'},{name:'value',type:'string',desc:'查询的车牌号或VIN'}],
      example:'{"value":"京A12345"}', response:'{"code":200,"msg":"success","data":{"new_date":"2024-12","old_date":"2023-01-16","value":"贵A99A47"}}' },

    { id:'nz_29', name:'车辆过户次数查询', desc:'通过车牌号或vin车架号查询车辆过户次数。', price:17.14, method:'POST', endpoint:'/api/nz/29',
      params:[{name:'value',type:'string',required:true,desc:'车牌号或VIN'}],
      responseParams:[{name:'guohu_num',type:'string',desc:'过户次数'},{name:'value',type:'string',desc:'查询的车辆标识'}],
      example:'{"value":"京A12345"}', response:'{"code":200,"msg":"success","data":{"guohu_num":"0次","value":"川A19A47"}}' },

    { id:'nz_61', name:'快递物流查询', desc:'实时物流轨迹跟踪服务，获取完整的快递物流信息。', price:0.02, method:'POST', endpoint:'/api/nz/61',
      params:[{name:'number',type:'string',required:true,desc:'运单编号'},{name:'sort',type:'string',required:false,desc:'排序 desc/asc'}],
      responseParams:[{name:'expressCompanyName',type:'string',desc:'快递公司名称'},{name:'logisticsStatusDesc',type:'string',desc:'物流状态'},{name:'theLastMessage',type:'string',desc:'最新物流信息'},{name:'logisticsTraceDetails',type:'array',desc:'物流轨迹数组'}],
      example:'{"number":"SF1234567890"}', response:'{"code":200,"msg":"success","data":{"expressCompanyName":"顺丰","logisticsStatusDesc":"运输中"}}' },

    { id:'nz_36', name:'主办单位+ICP号备案查询', desc:'根据主办单位或ICP号实时查询返回备案信息。', price:0.19, method:'POST', endpoint:'/api/nz/36',
      params:[{name:'name',type:'string',required:true,desc:'主办单位或ICP号'},{name:'page',type:'string',required:false,desc:'页数，默认1'}],
      responseParams:[{name:'count',type:'int',desc:'备案总数'},{name:'list',type:'array',desc:'备案记录数组'}],
      example:'{"name":"某某公司"}', response:'{"code":200,"msg":"success","data":{"page":1,"count":3,"list":[]}}' },

    { id:'nz_49', name:'实时查询百度收录量', desc:'根据域名返回百度收录量等相关信息。', price:0.05, method:'POST', endpoint:'/api/nz/49',
      params:[{name:'domain',type:'string',required:true,desc:'域名'}],
      responseParams:[{name:'domain',type:'string',desc:'域名'},{name:'count',type:'int',desc:'收录数量'}],
      example:'{"domain":"example.com"}', response:'{"code":200,"msg":"success","data":{"domain":"xxx.cn","count":71}}' },

    { id:'nz_50', name:'百度移动权重查询', desc:'返回百度移动搜索引擎的权重、预估流量、关键词数。', price:0.07, method:'POST', endpoint:'/api/nz/50',
      params:[{name:'domain',type:'string',required:true,desc:'域名'}],
      responseParams:[{name:'Br',type:'int',desc:'权重'},{name:'Kw_count',type:'int',desc:'关键词数'},{name:'Uv_count',type:'string',desc:'预估流量'},{name:'Up_date',type:'string',desc:'更新日期'}],
      example:'{"domain":"example.com"}', response:'{"code":200,"msg":"success","data":{"Br":2,"Kw_count":22}}' },

    { id:'nz_51', name:'企业名称模糊查询', desc:'通过企业名称关键字模糊查询企业工商注册基本信息。', price:0.69, method:'POST', endpoint:'/api/nz/51',
      params:[{name:'page',type:'string',required:false,desc:'页码，默认1'}],
      responseParams:[{name:'count',type:'int',desc:'总条数'},{name:'list',type:'array',desc:'企业列表'}],
      example:'{"page":"1"}', response:'{"code":200,"msg":"success","data":{"page":1,"count":54,"list":[]}}' },

    { id:'nz_52', name:'企业工商信息模糊查询', desc:'通过查询关键词智能多维度匹配工商信息。', price:0.69, method:'POST', endpoint:'/api/nz/52',
      params:[{name:'page',type:'string',required:false,desc:'页码，默认1'}],
      responseParams:[{name:'count',type:'int',desc:'总条数'},{name:'list',type:'array',desc:'企业列表'}],
      example:'{"page":"1"}', response:'{"code":200,"msg":"success","data":{"page":1,"count":33026,"list":[]}}' },

    { id:'nz_1', name:'ICP备案实时查询', desc:'根据域名实时返回查询域名的备案信息。', price:0.14, method:'POST', endpoint:'/api/nz/1',
      params:[{name:'domain',type:'string',required:true,desc:'域名'}],
      responseParams:[{name:'domain',type:'string',desc:'域名'},{name:'status',type:'int',desc:'1备案;2未备'},{name:'name',type:'string',desc:'备案主办单位名称'},{name:'icp',type:'string',desc:'备案号'},{name:'date',type:'string',desc:'备案日期'}],
      example:'{"domain":"qq.com"}', response:'{"code":200,"msg":"success","data":{"domain":"qq.com","status":1,"name":"深圳市腾讯计算机系统有限公司","icp":"粤B2-20090059-5"}}' },

    { id:'nz_16', name:'域名whois信息查询', desc:'域名whois注册信息查询。', price:0.10, method:'POST', endpoint:'/api/nz/16',
      params:[{name:'domain',type:'string',required:true,desc:'域名'}],
      responseParams:[{name:'name',type:'string',desc:'域名持有人'},{name:'email',type:'string',desc:'持有人邮箱'},{name:'dns',type:'string',desc:'DNS服务器'},{name:'registrars',type:'string',desc:'域名注册商'},{name:'Registration_Time',type:'string',desc:'域名创建时间'},{name:'Expiration_Time',type:'string',desc:'域名过期时间'}],
      example:'{"domain":"qq.cn"}', response:'{"code":200,"msg":"success","data":{"domain":"qq.cn","name":"****科技有限公司"}}' },

    { id:'nz_17', name:'网站标题TDK查询', desc:'网站标题描述关键词查询。免费接口。', price:0, method:'POST', endpoint:'/api/nz/17',
      params:[{name:'url',type:'string',required:true,desc:'网址'}],
      responseParams:[{name:'title',type:'string',desc:'网站标题'},{name:'keywords',type:'string',desc:'网站关键词'},{name:'description',type:'string',desc:'网站描述'}],
      example:'{"url":"https://example.com"}', response:'{"code":200,"msg":"success","data":{"title":"...","keywords":"...","description":"..."}}' },

    { id:'nz_13', name:'微信域名拦截查询', desc:'微信域名拦截状态查询。', price:0.01, method:'POST', endpoint:'/api/nz/13',
      params:[{name:'url',type:'string',required:true,desc:'域名或网址'}],
      responseParams:[{name:'type',type:'int',desc:'1:正常; 2:拦截'}],
      example:'{"url":"example.com"}', response:'{"code":200,"msg":"success","data":{"type":1,"type_msg":"正常"}}' },

    { id:'nz_12', name:'QQ域名拦截查询', desc:'QQ域名拦截状态查询。', price:0.01, method:'POST', endpoint:'/api/nz/12',
      params:[{name:'url',type:'string',required:true,desc:'域名或网址'}],
      responseParams:[{name:'type',type:'int',desc:'1:正常; 2:拦截'}],
      example:'{"url":"example.com"}', response:'{"code":200,"msg":"success","data":{"type":1,"type_msg":"正常"}}' },

    { id:'nz_5', name:'手机话费余额查询', desc:'话费余额综合查询（包含携号转网）。', price:0.51, method:'POST', endpoint:'/api/nz/5',
      params:[{name:'phone',type:'string',required:true,desc:'手机号'}],
      responseParams:[{name:'code',type:'int',desc:'200=成功'}],
      example:'{"phone":"13800138000"}', response:'{"code":200,"msg":"success","data":{}}' },

    { id:'nz_6', name:'手机号在网状态查询', desc:'查询手机号在网状态：空号、实号、停机、库无、沉默号、风险号等。', price:0.03, method:'POST', endpoint:'/api/nz/6',
      params:[{name:'phone',type:'string',required:true,desc:'手机号'}],
      responseParams:[{name:'yys',type:'string',desc:'运营商'},{name:'guishu',type:'string',desc:'归属地'},{name:'status',type:'int',desc:'0:空号; 1:实号; 4:停机; 5:沉默号; 6:风险号'},{name:'status_msg',type:'string',desc:'状态描述'}],
      example:'{"phone":"13800138000"}', response:'{"code":200,"msg":"success","data":{"phone":"17684244177","yys":"联通","status":1,"status_msg":"实号(正常)"}}' },

    { id:'nz_15', name:'手机号码归属地查询', desc:'号码归属地查询。', price:0.001, method:'POST', endpoint:'/api/nz/15',
      params:[{name:'phone',type:'string',required:true,desc:'手机号码'}],
      responseParams:[{name:'local',type:'string',desc:'号码归属地'},{name:'type',type:'string',desc:'卡类型'},{name:'yys',type:'string',desc:'运营商'}],
      example:'{"phone":"13800138000"}', response:'{"code":200,"msg":"success","data":{"local":"浙江省杭州市","type":"浙江移动GSM卡","yys":"中国移动"}}' },

    { id:'nz_37', name:'手机号使用时长查询', desc:'查询手机号在网时长。', price:1.71, method:'POST', endpoint:'/api/nz/37',
      params:[{name:'phone',type:'string',required:true,desc:'手机号'}],
      responseParams:[{name:'yys',type:'string',desc:'运营商'},{name:'time',type:'string',desc:'在网时长'}],
      example:'{"phone":"13800138000"}', response:'{"code":200,"msg":"success","data":{"yys":"联通","time":"俩年以上"}}' },

    { id:'nz_22', name:'车牌号码查归属地区', desc:'通过车牌号查询该车牌号对应的地区。免费接口。', price:0, method:'POST', endpoint:'/api/nz/22',
      params:[{name:'chepai',type:'string',required:true,desc:'车牌号码'}],
      responseParams:[{name:'location',type:'string',desc:'归属地'},{name:'chepai',type:'string',desc:'车牌号'}],
      example:'{"chepai":"川A"}', response:'{"code":200,"msg":"success","data":{"chepai":"川A","location":"四川省成都市"}}' },

    { id:'nz_66', name:'人脸实名认证', desc:'与公安库身份证头像进行权威比对核验。', price:0.81, method:'POST', endpoint:'/api/nz/66',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'idcard',type:'string',required:true,desc:'身份证号'},{name:'file_url',type:'string',required:true,desc:'人脸照片地址'}],
      responseParams:[{name:'score',type:'int',desc:'人脸比对分值 0-100'},{name:'verify',type:'int',desc:'1=同一人; 2=可能为同一人; 3=不同人'},{name:'message',type:'string',desc:'结果文字说明'}],
      example:'{"name":"张三","idcard":"110101199001011234","file_url":"https://example.com/face.jpg"}', response:'{"code":200,"msg":"success","data":{"score":95,"verify":1,"message":"系统判断为同一人"}}' },

    { id:'nz_60', name:'企业任职记录', desc:'查询关联企业，一键实时查询名下企业。', price:5.71, method:'POST', endpoint:'/api/nz/60',
      params:[{name:'idcard',type:'string',required:true,desc:'身份证号'},{name:'name',type:'string',required:false,desc:'姓名'}],
      responseParams:[{name:'totalCount',type:'int',desc:'任职关联企业总数'},{name:'list',type:'array',desc:'关联企业任职记录数组'}],
      example:'{"idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"totalCount":1,"list":[]}}' },

    { id:'nz_62', name:'司法综合数据查询', desc:'全国法院司法数据一站式检索，支持6大核心司法数据查询。', price:1.71, method:'POST', endpoint:'/api/nz/62',
      params:[{name:'name',type:'string',required:false,desc:'姓名或企业名称'},{name:'idcard',type:'string',required:false,desc:'证件号或统一社会信用代码'}],
      responseParams:[{name:'shixin_count',type:'int',desc:'失信记录数'},{name:'zhixing_count',type:'int',desc:'被执行记录数'},{name:'shixin_list',type:'array',desc:'失信被执行人记录'}],
      example:'{"name":"张三"}', response:'{"code":200,"msg":"success","data":{"shixin_count":1,"zhixing_count":1}}' },

    { id:'nz_53', name:'企业工商信息标准版', desc:'根据公司名全称、注册号、社会统一信用代码查询企业工商信息。', price:0.86, method:'POST', endpoint:'/api/nz/53',
      params:[{name:'name',type:'string',required:true,desc:'公司名全称、注册号、信用代码'}],
      responseParams:[{name:'data.companyName',type:'string',desc:'企业名称'},{name:'data.legalPerson',type:'string',desc:'法定代表人'},{name:'data.capital',type:'string',desc:'注册资本'},{name:'data.companyStatus',type:'string',desc:'经营状态'}],
      example:'{"name":"某某有限公司"}', response:'{"code":200,"msg":"success","data":{"companyName":"示例科技有限公司"}}' },

    { id:'nz_23', name:'银行卡归属地查询', desc:'通过银行卡号查询银行卡归属地、卡种、卡类型、银行名称等。', price:0.03, method:'POST', endpoint:'/api/nz/23',
      params:[{name:'cardno',type:'string',required:true,desc:'银行卡号'}],
      responseParams:[{name:'name',type:'string',desc:'银行名称'},{name:'abbr',type:'string',desc:'银行英文缩写'},{name:'card_name',type:'string',desc:'银行卡名称'},{name:'card_type',type:'string',desc:'银行卡类型'},{name:'phone',type:'string',desc:'银行客服电话'},{name:'area',type:'string',desc:'开卡地区'}],
      example:'{"cardno":"6217000010000000000"}', response:'{"code":200,"msg":"success","data":{"name":"中国银行","abbr":"BOC"}}' },

    { id:'nz_11', name:'vin车架号解析车辆信息', desc:'车架号/VIN码在线解析车辆相关信息。', price:0.24, method:'POST', endpoint:'/api/nz/11',
      params:[{name:'vin',type:'string',required:true,desc:'VIN车架号'}],
      responseParams:[{name:'name_info',type:'string',desc:'汽车型号'},{name:'pailiang',type:'string',desc:'车辆排量'},{name:'market_price',type:'string',desc:'市场价格'},{name:'fuel_type',type:'string',desc:'燃油类型'}],
      example:'{"vin":"WP0AB2978PL130045"}', response:'{"code":200,"msg":"success","data":{"name_info":"Panamera 2023款","pailiang":"2.9T"}}' },

    { id:'nz_2', name:'车牌号查车五项信息+使用性质', desc:'车牌号查询车五项信息（车架号、车辆种类、车辆品牌、初登日期）+使用性质。', price:2.46, method:'POST', endpoint:'/api/nz/2',
      params:[{name:'chepai',type:'string',required:true,desc:'车牌号'}],
      responseParams:[{name:'vin',type:'string',desc:'vin车架号'},{name:'date',type:'string',desc:'初登日期'},{name:'type',type:'string',desc:'车辆种类'},{name:'usage',type:'string',desc:'使用性质'},{name:'name',type:'string',desc:'车辆品牌'}],
      example:'{"chepai":"京A12345"}', response:'{"code":200,"msg":"success","data":{"name":"保时捷","type":"乘用车"}}' },

    { id:'nz_7', name:'车牌解析车辆信息', desc:'车牌解析车辆多项信息（品牌、型号、发动机、车架号等）。', price:2.57, method:'POST', endpoint:'/api/nz/7',
      params:[{name:'chepai',type:'string',required:true,desc:'车牌号'}],
      responseParams:[{name:'name',type:'string',desc:'车辆品牌'},{name:'name_info',type:'string',desc:'汽车型号'},{name:'vin',type:'string',desc:'vin车架号'},{name:'date',type:'string',desc:'初登日期'}],
      example:'{"chepai":"京A12345"}', response:'{"code":200,"msg":"success","data":{"name":"保时捷"}}' },

    { id:'nz_21', name:'银行卡二三四要素检验', desc:'银行卡实名验证，输入姓名和银行卡号，银联渠道实时校验。', price:1.09, method:'POST', endpoint:'/api/nz/21',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'acct_no',type:'string',required:true,desc:'银行卡号'},{name:'idcard',type:'string',required:false,desc:'身份证号'},{name:'phone',type:'string',required:false,desc:'手机号码'}],
      responseParams:[{name:'state',type:'string',desc:'1:一致; 2:不一致; 3-8:异常'}],
      example:'{"name":"张三","acct_no":"6217000010000000000"}', response:'{"code":200,"msg":"success","data":{"state":"1"}}' },

    { id:'nz_42', name:'名下ETC车辆查询', desc:'根据证件号码查询名下ETC车辆详情。', price:6.29, method:'POST', endpoint:'/api/nz/42',
      params:[{name:'value',type:'string',required:true,desc:'身份证号'},{name:'name',type:'string',required:false,desc:'姓名'}],
      responseParams:[{name:'mingxia_num',type:'int',desc:'名下ETC车辆数量'},{name:'list',type:'array',desc:'车牌号列表'}],
      example:'{"value":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"mingxia_num":2,"list":["京A5****","京B8****"]}}' },

    { id:'nz_38', name:'婚姻状态', desc:'查询个人婚姻状态及婚姻登记日期。', price:10.86, method:'POST', endpoint:'/api/nz/38',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'idcard',type:'string',required:true,desc:'身份证号'}],
      responseParams:[{name:'status',type:'string',desc:'1=已婚, 2=单身, 3=离婚'},{name:'status_msg',type:'string',desc:'已、单、离'},{name:'reg_Time',type:'string',desc:'婚姻登记日期'}],
      example:'{"name":"张三","idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"status":"1","status_msg":"已","reg_Time":"2004-12-23"}}' },

    { id:'nz_4', name:'身份证实名检验', desc:'身份证二要素核验，身份证实名验证。', price:0.13, method:'POST', endpoint:'/api/nz/4',
      params:[{name:'name',type:'string',required:true,desc:'姓名'},{name:'idcard',type:'string',required:true,desc:'身份证号'}],
      responseParams:[{name:'status',type:'string',desc:'1:验证一致; 2:不一致; 3:异常情况'},{name:'name',type:'string',desc:'本次核验的姓名'}],
      example:'{"name":"张三","idcard":"110101199001011234"}', response:'{"code":200,"msg":"success","data":{"name":"姓名","status":"2"}}' },

    // ==================== UApiPro 平台 ====================
    { id:'uapi_1', name:'查询天气', desc:'查询城市天气', price:0.02, method:'GET', endpoint:'/api/uapi/weather', params:[{name:'city',type:'string',required:true,desc:'城市名'}], example:'{"city":"北京"}' },
    { id:'uapi_2', name:'一言', desc:'随机一言', price:0, method:'GET', endpoint:'/api/uapi/yiyan', params:[], example:'{}' },
    { id:'uapi_3', name:'查询世界时间', desc:'世界时间查询', price:0.01, method:'GET', endpoint:'/api/uapi/worldtime', params:[], example:'{}' },
    { id:'uapi_4', name:'查询热榜', desc:'全网热榜', price:0.01, method:'GET', endpoint:'/api/uapi/hot', params:[], example:'{}' },
    { id:'uapi_5', name:'单词查询', desc:'英文单词查询', price:0.01, method:'GET', endpoint:'/api/uapi/dict', params:[{name:'word',type:'string',required:true,desc:'单词'}], example:'{"word":"hello"}' },
    { id:'uapi_6', name:'查询QQ信息', desc:'QQ信息查询', price:0.01, method:'GET', endpoint:'/api/uapi/qq', params:[{name:'qq',type:'string',required:true,desc:'QQ号'}], example:'{"qq":"123456"}' },
    { id:'uapi_7', name:'随机图片', desc:'随机图片', price:0, method:'GET', endpoint:'/api/uapi/randomimg', params:[], example:'{}' },
    { id:'uapi_8', name:'查询我的IP', desc:'查询当前IP', price:0, method:'GET', endpoint:'/api/uapi/myip', params:[], example:'{}' },
    { id:'uapi_9', name:'查询B站直播间', desc:'B站直播间信息', price:0.01, method:'GET', endpoint:'/api/uapi/bilibili/live', params:[{name:'roomid',type:'string',required:true,desc:'直播间ID'}], example:'{"roomid":"12345"}' },
    { id:'uapi_10', name:'敏感词检测（快速）', desc:'敏感词快速检测', price:0.01, method:'POST', endpoint:'/api/uapi/sensitive/quick', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"测试"}' },
    { id:'uapi_11', name:'查询B站用户', desc:'B站用户信息', price:0.01, method:'GET', endpoint:'/api/uapi/bilibili/user', params:[{name:'uid',type:'string',required:true,desc:'B站UID'}], example:'{"uid":"123456"}' },
    { id:'uapi_12', name:'查询手机归属地', desc:'手机号归属地查询', price:0.01, method:'GET', endpoint:'/api/uapi/phone', params:[{name:'phone',type:'string',required:true,desc:'手机号'}], example:'{"phone":"13800138000"}' },
    { id:'uapi_13', name:'查询MC服务器', desc:'Minecraft服务器状态', price:0.01, method:'GET', endpoint:'/api/uapi/mc/server', params:[{name:'host',type:'string',required:true,desc:'服务器地址'}], example:'{"host":"mc.hypixel.net"}' },
    { id:'uapi_14', name:'查询IP', desc:'IP地址查询', price:0, method:'GET', endpoint:'/api/uapi/ip', params:[{name:'ip',type:'string',required:true,desc:'IP地址'}], example:'{"ip":"8.8.8.8"}' },
    { id:'uapi_15', name:'翻译', desc:'中英翻译', price:0.01, method:'POST', endpoint:'/api/uapi/translate', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"你好"}' },
    { id:'uapi_16', name:'获取API端点使用统计', desc:'API端点使用统计', price:0, method:'GET', endpoint:'/api/uapi/stats', params:[], example:'{}' },
    { id:'uapi_17', name:'查询QQ群信息', desc:'QQ群信息查询', price:0.01, method:'GET', endpoint:'/api/uapi/qqgroup', params:[{name:'group',type:'string',required:true,desc:'群号'}], example:'{"group":"123456"}' },
    { id:'uapi_18', name:'查询B站投稿', desc:'B站投稿查询', price:0.01, method:'GET', endpoint:'/api/uapi/bilibili/post', params:[{name:'uid',type:'string',required:true,desc:'UID'}], example:'{"uid":"123456"}' },
    { id:'uapi_19', name:'查询B站视频', desc:'B站视频信息', price:0.01, method:'GET', endpoint:'/api/uapi/bilibili/video', params:[{name:'bvid',type:'string',required:true,desc:'BV号'}], example:'{"bvid":"BV1xx"}' },
    { id:'uapi_20', name:'查询域名ICP备案信息', desc:'ICP备案查询', price:0.01, method:'GET', endpoint:'/api/uapi/icp', params:[{name:'domain',type:'string',required:true,desc:'域名'}], example:'{"domain":"qq.com"}' },
    { id:'uapi_21', name:'MD5哈希', desc:'MD5哈希计算', price:0, method:'GET', endpoint:'/api/uapi/md5', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"abc"}' },
    { id:'uapi_22', name:'MD5哈希(POST)', desc:'MD5哈希计算', price:0, method:'POST', endpoint:'/api/uapi/md5post', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"abc"}' },
    { id:'uapi_23', name:'获取必应每日壁纸', desc:'必应每日壁纸', price:0, method:'GET', endpoint:'/api/uapi/bing', params:[], example:'{}' },
    { id:'uapi_24', name:'程序员历史上的今天', desc:'程序员历史事件', price:0.01, method:'GET', endpoint:'/api/uapi/programmer/today', params:[], example:'{}' },
    { id:'uapi_25', name:'查询B站评论', desc:'B站评论查询', price:0.01, method:'GET', endpoint:'/api/uapi/bilibili/comment', params:[{name:'bvid',type:'string',required:true,desc:'BV号'}], example:'{"bvid":"BV1xx"}' },
    { id:'uapi_26', name:'查询域名的WHOIS注册信息', desc:'WHOIS查询', price:0.01, method:'GET', endpoint:'/api/uapi/whois', params:[{name:'domain',type:'string',required:true,desc:'域名'}], example:'{"domain":"qq.com"}' },
    { id:'uapi_27', name:'查询Steam用户', desc:'Steam用户信息', price:0.01, method:'GET', endpoint:'/api/uapi/steam/user', params:[{name:'steamid',type:'string',required:true,desc:'SteamID'}], example:'{"steamid":"7656119"}' },
    { id:'uapi_28', name:'查询MC玩家', desc:'Minecraft玩家信息', price:0.01, method:'GET', endpoint:'/api/uapi/mc/player', params:[{name:'name',type:'string',required:true,desc:'玩家名'}], example:'{"name":"Notch"}' },
    { id:'uapi_29', name:'答案之书', desc:'随机答案', price:0, method:'GET', endpoint:'/api/uapi/answer', params:[], example:'{}' },
    { id:'uapi_30', name:'答案之书(POST)', desc:'随机答案', price:0, method:'POST', endpoint:'/api/uapi/answerpost', params:[], example:'{}' },
    { id:'uapi_31', name:'智能搜索', desc:'智能搜索', price:0.02, method:'POST', endpoint:'/api/uapi/smartsearch', params:[{name:'q',type:'string',required:true,desc:'关键词'}], example:'{"q":"天气"}' },
    { id:'uapi_32', name:'随机数生成', desc:'随机数生成', price:0, method:'GET', endpoint:'/api/uapi/random', params:[], example:'{}' },
    { id:'uapi_33', name:'AI智能翻译', desc:'AI翻译', price:0.02, method:'POST', endpoint:'/api/uapi/aitranslate', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"你好"}' },
    { id:'uapi_34', name:'文本分析', desc:'文本分析', price:0.01, method:'POST', endpoint:'/api/uapi/textanalyze', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"你好"}' },
    { id:'uapi_35', name:'查询农历时间', desc:'农历时间查询', price:0.01, method:'GET', endpoint:'/api/uapi/lunar', params:[], example:'{}' },
    { id:'uapi_36', name:'生成二维码', desc:'二维码生成', price:0.01, method:'GET', endpoint:'/api/uapi/qrcode', params:[{name:'text',type:'string',required:true,desc:'内容'}], example:'{"text":"https://example.com"}' },
    { id:'uapi_37', name:'一言（随机/每日/场景/此刻）', desc:'一言多模式', price:0, method:'GET', endpoint:'/api/uapi/yiyan/multi', params:[], example:'{}' },
    { id:'uapi_38', name:'图片敏感检测', desc:'图片敏感检测', price:0.01, method:'POST', endpoint:'/api/uapi/imgsensitive', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_39', name:'Ping主机', desc:'Ping主机', price:0.01, method:'GET', endpoint:'/api/uapi/ping', params:[{name:'host',type:'string',required:true,desc:'主机'}], example:'{"host":"baidu.com"}' },
    { id:'uapi_40', name:'每日新闻图', desc:'每日新闻图', price:0, method:'GET', endpoint:'/api/uapi/newsimg', params:[], example:'{}' },
    { id:'uapi_41', name:'Epic免费游戏', desc:'Epic免费游戏', price:0.01, method:'GET', endpoint:'/api/uapi/epic', params:[], example:'{}' },
    { id:'uapi_42', name:'程序员历史事件', desc:'程序员历史事件', price:0.01, method:'GET', endpoint:'/api/uapi/programmer/event', params:[], example:'{}' },
    { id:'uapi_43', name:'单词发音', desc:'单词发音', price:0.01, method:'GET', endpoint:'/api/uapi/word/audio', params:[{name:'word',type:'string',required:true,desc:'单词'}], example:'{"word":"hello"}' },
    { id:'uapi_44', name:'执行DNS解析查询', desc:'DNS解析查询', price:0.01, method:'GET', endpoint:'/api/uapi/dns', params:[{name:'domain',type:'string',required:true,desc:'域名'}], example:'{"domain":"qq.com"}' },
    { id:'uapi_45', name:'通过Base64编码上传图片', desc:'Base64图片上传', price:0.01, method:'POST', endpoint:'/api/uapi/upload/base64', params:[{name:'base64',type:'string',required:true,desc:'Base64字符串'}], example:'{"base64":"..."}' },
    { id:'uapi_46', name:'检查URL的可访问性状态', desc:'URL可访问性检测', price:0.01, method:'GET', endpoint:'/api/uapi/urlcheck', params:[{name:'url',type:'string',required:true,desc:'URL'}], example:'{"url":"https://example.com"}' },
    { id:'uapi_47', name:'图片转Base64', desc:'图片转Base64', price:0.01, method:'GET', endpoint:'/api/uapi/img2base64', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_48', name:'在线运行代码', desc:'在线运行代码', price:0.02, method:'POST', endpoint:'/api/uapi/runcode', params:[{name:'code',type:'string',required:true,desc:'代码'}], example:'{"code":"print(1)"}' },
    { id:'uapi_49', name:'端口扫描', desc:'端口扫描', price:0.02, method:'GET', endpoint:'/api/uapi/portscan', params:[{name:'host',type:'string',required:true,desc:'主机'}], example:'{"host":"example.com"}' },
    { id:'uapi_50', name:'获取Gravatar头像', desc:'Gravatar头像', price:0, method:'GET', endpoint:'/api/uapi/gravatar', params:[{name:'email',type:'string',required:true,desc:'邮箱'}], example:'{"email":"test@test.com"}' },
    { id:'uapi_51', name:'提取网页元数据', desc:'网页元数据提取', price:0.01, method:'GET', endpoint:'/api/uapi/webmeta', params:[{name:'url',type:'string',required:true,desc:'URL'}], example:'{"url":"https://example.com"}' },
    { id:'uapi_52', name:'查询GitHub仓库', desc:'GitHub仓库查询', price:0.01, method:'GET', endpoint:'/api/uapi/github/repo', params:[{name:'repo',type:'string',required:true,desc:'仓库名'}], example:'{"repo":"torvalds/linux"}' },
    { id:'uapi_53', name:'AI翻译配置', desc:'AI翻译配置', price:0, method:'GET', endpoint:'/api/uapi/aitranslate/config', params:[], example:'{}' },
    { id:'uapi_54', name:'检查域名在微信中的访问状态', desc:'微信域名检测', price:0.01, method:'GET', endpoint:'/api/uapi/wechat/domain', params:[{name:'url',type:'string',required:true,desc:'域名'}], example:'{"url":"qq.com"}' },
    { id:'uapi_55', name:'分析敏感词', desc:'敏感词分析', price:0.01, method:'POST', endpoint:'/api/uapi/sensitive/analyze', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"测试"}' },
    { id:'uapi_56', name:'查询节假日与万年历', desc:'节假日万年历', price:0.01, method:'GET', endpoint:'/api/uapi/holiday', params:[], example:'{}' },
    { id:'uapi_57', name:'随机字符串', desc:'随机字符串', price:0, method:'GET', endpoint:'/api/uapi/randomstr', params:[], example:'{}' },
    { id:'uapi_58', name:'生成摸摸头GIF', desc:'摸摸头GIF', price:0.02, method:'POST', endpoint:'/api/uapi/momogif', params:[{name:'url',type:'string',required:true,desc:'头像URL'}], example:'{"url":"https://example.com/avatar.jpg"}' },
    { id:'uapi_59', name:'生成摸摸头GIF(QQ号)', desc:'摸摸头GIF', price:0.02, method:'GET', endpoint:'/api/uapi/momogif/qq', params:[{name:'qq',type:'string',required:true,desc:'QQ号'}], example:'{"qq":"123456"}' },
    { id:'uapi_60', name:'时间戳转换', desc:'时间戳转换', price:0, method:'GET', endpoint:'/api/uapi/timestamp', params:[], example:'{}' },
    { id:'uapi_61', name:'查询MC曾用名', desc:'MC曾用名查询', price:0.01, method:'GET', endpoint:'/api/uapi/mc/name', params:[{name:'name',type:'string',required:true,desc:'玩家名'}], example:'{"name":"Notch"}' },
    { id:'uapi_62', name:'Ping我的IP', desc:'Ping我的IP', price:0, method:'GET', endpoint:'/api/uapi/ping/myip', params:[], example:'{}' },
    { id:'uapi_63', name:'搜索引擎配置', desc:'搜索引擎配置', price:0, method:'GET', endpoint:'/api/uapi/search/config', params:[], example:'{}' },
    { id:'uapi_64', name:'提取网页图片', desc:'网页图片提取', price:0.01, method:'GET', endpoint:'/api/uapi/webimg', params:[{name:'url',type:'string',required:true,desc:'URL'}], example:'{"url":"https://example.com"}' },
    { id:'uapi_65', name:'敏感词分析(GET)', desc:'敏感词分析', price:0.01, method:'GET', endpoint:'/api/uapi/sensitive/analyze/get', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"测试"}' },
    { id:'uapi_66', name:'Base64解码', desc:'Base64解码', price:0, method:'POST', endpoint:'/api/uapi/base64/decode', params:[{name:'text',type:'string',required:true,desc:'Base64字符串'}], example:'{"text":"aGVsbG8="}' },
    { id:'uapi_67', name:'JSON格式化', desc:'JSON格式化', price:0, method:'POST', endpoint:'/api/uapi/json/format', params:[{name:'json',type:'string',required:true,desc:'JSON字符串'}], example:'{"json":"{\"a\":1}"}' },
    { id:'uapi_68', name:'Base64编码', desc:'Base64编码', price:0, method:'POST', endpoint:'/api/uapi/base64/encode', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"hello"}' },
    { id:'uapi_69', name:'AES加密', desc:'AES加密', price:0.01, method:'POST', endpoint:'/api/uapi/aes/encrypt', params:[{name:'text',type:'string',required:true,desc:'文本'},{name:'key',type:'string',required:true,desc:'密钥'}], example:'{"text":"hello","key":"1234567890abcdef"}' },
    { id:'uapi_70', name:'转换时间戳(旧版)', desc:'时间戳转换', price:0, method:'GET', endpoint:'/api/uapi/unixtime', params:[], example:'{}' },
    { id:'uapi_71', name:'AES解密', desc:'AES解密', price:0.01, method:'POST', endpoint:'/api/uapi/aes/decrypt', params:[{name:'text',type:'string',required:true,desc:'密文'},{name:'key',type:'string',required:true,desc:'密钥'}], example:'{"text":"...","key":"1234567890abcdef"}' },
    { id:'uapi_72', name:'MD5校验', desc:'MD5校验', price:0, method:'POST', endpoint:'/api/uapi/md5/check', params:[{name:'text',type:'string',required:true,desc:'文本'},{name:'md5',type:'string',required:true,desc:'MD5值'}], example:'{"text":"abc","md5":"..."}' },
    { id:'uapi_73', name:'网页转Markdown', desc:'网页转Markdown', price:0.01, method:'POST', endpoint:'/api/uapi/html2markdown', params:[{name:'url',type:'string',required:true,desc:'URL'}], example:'{"url":"https://example.com"}' },
    { id:'uapi_74', name:'查询快递物流信息', desc:'快递物流查询', price:0.01, method:'GET', endpoint:'/api/uapi/express', params:[{name:'number',type:'string',required:true,desc:'快递单号'}], example:'{"number":"SF1234567890"}' },
    { id:'uapi_75', name:'无损压缩图片', desc:'图片压缩', price:0.02, method:'POST', endpoint:'/api/uapi/img/compress', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_76', name:'Adcode国内外行政区域查询', desc:'行政区域查询', price:0.01, method:'GET', endpoint:'/api/uapi/adcode', params:[], example:'{}' },
    { id:'uapi_77', name:'计算两个日期之间的时间差值', desc:'日期差值计算', price:0, method:'POST', endpoint:'/api/uapi/date/diff', params:[{name:'start',type:'string',required:true,desc:'开始日期'},{name:'end',type:'string',required:true,desc:'结束日期'}], example:'{"start":"2024-01-01","end":"2024-12-31"}' },
    { id:'uapi_78', name:'菜谱详情', desc:'菜谱详情', price:0.01, method:'GET', endpoint:'/api/uapi/caipu/detail', params:[{name:'id',type:'string',required:true,desc:'菜谱ID'}], example:'{"id":"1"}' },
    { id:'uapi_79', name:'通用OCR文字识别', desc:'OCR文字识别', price:0.02, method:'POST', endpoint:'/api/uapi/ocr', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_80', name:'查询电影票房', desc:'电影票房查询', price:0.01, method:'GET', endpoint:'/api/uapi/movie/box', params:[], example:'{}' },
    { id:'uapi_81', name:'查询历史天气', desc:'历史天气查询', price:0.01, method:'GET', endpoint:'/api/uapi/weather/history', params:[{name:'city',type:'string',required:true,desc:'城市'},{name:'date',type:'string',required:true,desc:'日期'}], example:'{"city":"北京","date":"2024-01-01"}' },
    { id:'uapi_82', name:'每日单词', desc:'每日单词', price:0, method:'GET', endpoint:'/api/uapi/word/daily', params:[], example:'{}' },
    { id:'uapi_83', name:'步骤1：上传加密数据', desc:'加密数据上传', price:0.01, method:'POST', endpoint:'/api/uapi/encrypt/upload', params:[{name:'data',type:'string',required:true,desc:'数据'}], example:'{"data":"..."}' },
    { id:'uapi_84', name:'步骤2(方法二)：获取原始文本', desc:'获取原始文本', price:0.01, method:'GET', endpoint:'/api/uapi/encrypt/text', params:[], example:'{}' },
    { id:'uapi_85', name:'步骤2(方法一)：获取加密数据', desc:'获取加密数据', price:0.01, method:'GET', endpoint:'/api/uapi/encrypt/data', params:[], example:'{}' },
    { id:'uapi_86', name:'菜谱搜索', desc:'菜谱搜索', price:0.01, method:'GET', endpoint:'/api/uapi/caipu/search', params:[{name:'keyword',type:'string',required:true,desc:'关键词'}], example:'{"keyword":"红烧肉"}' },
    { id:'uapi_87', name:'查询AI模型列表', desc:'AI模型列表', price:0, method:'GET', endpoint:'/api/uapi/ai/models', params:[], example:'{}' },
    { id:'uapi_88', name:'查询GitHub用户信息', desc:'GitHub用户信息', price:0.01, method:'GET', endpoint:'/api/uapi/github/user', params:[{name:'username',type:'string',required:true,desc:'用户名'}], example:'{"username":"torvalds"}' },
    { id:'uapi_89', name:'查询MC基岩版服务器', desc:'MC基岩版服务器', price:0.01, method:'GET', endpoint:'/api/uapi/mc/bedrock', params:[{name:'host',type:'string',required:true,desc:'服务器地址'}], example:'{"host":"mc.example.com"}' },
    { id:'uapi_90', name:'查询Steam游戏服务器', desc:'Steam游戏服务器', price:0.01, method:'GET', endpoint:'/api/uapi/steam/server', params:[{name:'host',type:'string',required:true,desc:'服务器地址'}], example:'{"host":"example.com"}' },
    { id:'uapi_91', name:'查询必应壁纸历史', desc:'必应壁纸历史', price:0.01, method:'GET', endpoint:'/api/uapi/bing/history', params:[], example:'{}' },
    { id:'uapi_92', name:'词典推荐语', desc:'词典推荐语', price:0, method:'GET', endpoint:'/api/uapi/dict/recommend', params:[], example:'{}' },
    { id:'uapi_93', name:'电影收视排行查询', desc:'电影收视排行', price:0.01, method:'GET', endpoint:'/api/uapi/movie/rank', params:[], example:'{}' },
    { id:'uapi_94', name:'格式转换', desc:'格式转换', price:0.02, method:'POST', endpoint:'/api/uapi/format/convert', params:[{name:'data',type:'string',required:true,desc:'数据'},{name:'from',type:'string',required:true,desc:'源格式'},{name:'to',type:'string',required:true,desc:'目标格式'}], example:'{"data":"...","from":"json","to":"yaml"}' },
    { id:'uapi_95', name:'获取支持的快递公司列表', desc:'快递公司列表', price:0, method:'GET', endpoint:'/api/uapi/express/companies', params:[], example:'{}' },
    { id:'uapi_96', name:'解码并缩放图片', desc:'图片解码缩放', price:0.02, method:'POST', endpoint:'/api/uapi/img/decode', params:[{name:'url',type:'string',required:true,desc:'图片URL'},{name:'width',type:'int',required:true,desc:'宽度'}], example:'{"url":"https://example.com/img.jpg","width":200}' },
    { id:'uapi_97', name:'流式翻译（中英互译）', desc:'流式翻译', price:0.02, method:'POST', endpoint:'/api/uapi/translate/stream', params:[{name:'text',type:'string',required:true,desc:'文本'}], example:'{"text":"你好"}' },
    { id:'uapi_98', name:'生成AIGC服务提供者编码', desc:'AIGC编码生成', price:0.01, method:'POST', endpoint:'/api/uapi/aigc/code', params:[], example:'{}' },
    { id:'uapi_99', name:'生成你们怎么不说话了表情包', desc:'表情包生成', price:0.02, method:'POST', endpoint:'/api/uapi/meme/silent', params:[], example:'{}' },
    { id:'uapi_100', name:'识别快递公司', desc:'快递公司识别', price:0.01, method:'GET', endpoint:'/api/uapi/express/identify', params:[{name:'number',type:'string',required:true,desc:'快递单号'}], example:'{"number":"SF1234567890"}' },
    { id:'uapi_101', name:'食材搜索', desc:'食材搜索', price:0.01, method:'GET', endpoint:'/api/uapi/food/search', params:[{name:'keyword',type:'string',required:true,desc:'关键词'}], example:'{"keyword":"鸡"}' },
    { id:'uapi_102', name:'食材营养详情', desc:'食材营养详情', price:0.01, method:'GET', endpoint:'/api/uapi/food/nutrition', params:[{name:'id',type:'string',required:true,desc:'食材ID'}], example:'{"id":"1"}' },
    { id:'uapi_103', name:'搜索MC Mod/插件', desc:'MC Mod搜索', price:0.01, method:'GET', endpoint:'/api/uapi/mc/mod', params:[{name:'keyword',type:'string',required:true,desc:'关键词'}], example:'{"keyword":"forge"}' },
    { id:'uapi_104', name:'提取图片隐水印', desc:'隐水印提取', price:0.02, method:'POST', endpoint:'/api/uapi/img/watermark/extract', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_105', name:'添加AI生成内容标识', desc:'AI内容标识添加', price:0.02, method:'POST', endpoint:'/api/uapi/aigc/mark', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_106', name:'添加图片隐水印', desc:'图片隐水印添加', price:0.02, method:'POST', endpoint:'/api/uapi/img/watermark/add', params:[{name:'url',type:'string',required:true,desc:'图片URL'},{name:'text',type:'string',required:true,desc:'水印文本'}], example:'{"url":"https://example.com/img.jpg","text":"版权"}' },
    { id:'uapi_107', name:'图片抠图（背景移除）', desc:'图片抠图', price:0.02, method:'POST', endpoint:'/api/uapi/img/removebg', params:[{name:'url',type:'string',required:true,desc:'图片URL'}], example:'{"url":"https://example.com/img.jpg"}' },
    { id:'uapi_108', name:'限流状态', desc:'限流状态查询', price:0, method:'GET', endpoint:'/api/uapi/ratelimit', params:[], example:'{}' },
    { id:'uapi_109', name:'转换任务状态', desc:'转换任务状态', price:0, method:'GET', endpoint:'/api/uapi/task/status', params:[{name:'id',type:'string',required:true,desc:'任务ID'}], example:'{"id":"1"}' },
    { id:'uapi_110', name:'AES高级加密', desc:'AES高级加密', price:0.01, method:'POST', endpoint:'/api/uapi/aes/advanced/encrypt', params:[{name:'text',type:'string',required:true,desc:'文本'},{name:'key',type:'string',required:true,desc:'密钥'}], example:'{"text":"hello","key":"..."}' },
    { id:'uapi_111', name:'AES高级解密', desc:'AES高级解密', price:0.01, method:'POST', endpoint:'/api/uapi/aes/advanced/decrypt', params:[{name:'text',type:'string',required:true,desc:'密文'},{name:'key',type:'string',required:true,desc:'密钥'}], example:'{"text":"...","key":"..."}' },
    { id:'uapi_112', name:'Markdown转HTML', desc:'Markdown转HTML', price:0.01, method:'POST', endpoint:'/api/uapi/markdown2html', params:[{name:'markdown',type:'string',required:true,desc:'Markdown文本'}], example:'{"markdown":"# Hello"}' },
    { id:'uapi_113', name:'Markdown转PDF', desc:'Markdown转PDF', price:0.02, method:'POST', endpoint:'/api/uapi/markdown2pdf', params:[{name:'markdown',type:'string',required:true,desc:'Markdown文本'}], example:'{"markdown":"# Hello"}' },
    { id:'uapi_114', name:'Minecraft最新版本', desc:'MC最新版本', price:0, method:'GET', endpoint:'/api/uapi/mc/version', params:[], example:'{}' },
    { id:'uapi_115', name:'SVG转图片', desc:'SVG转图片', price:0.01, method:'POST', endpoint:'/api/uapi/svg2img', params:[{name:'svg',type:'string',required:true,desc:'SVG代码'}], example:'{"svg":"<svg>...</svg>"}' }
  ],

  service: [
    { id:'nz_56', name:'实时汇率转换', desc:'实时人民币汇率转换，货币汇率查询。', price:0.01, method:'POST', endpoint:'/api/nz/56',
      params:[{name:'from_Code',type:'string',required:true,desc:'源货币编码'},{name:'money',type:'string',required:true,desc:'源货币金额'},{name:'to_Code',type:'string',required:false,desc:'目标货币编码，留空为CNY'}],
      responseParams:[{name:'money',type:'string',desc:'转换后的金额，单位元'},{name:'code',type:'int',desc:'200=成功'}],
      example:'{"from_Code":"USD","money":"100","to_Code":"CNY"}', response:'{"code":200,"msg":"success","data":{"money":"708.84"}}' },

    { id:'nz_58', name:'彩票开奖查询', desc:'彩票查询接口可查询各类彩票中奖情况，支持八类彩种。', price:0.01, method:'POST', endpoint:'/api/nz/58',
      params:[{name:'type',type:'string',required:true,desc:'ssq/qlc/fc3d/cjdlt/qxc/pl3/pl5/kl8'},{name:'qihao',type:'string',required:false,desc:'彩票期号'}],
      responseParams:[{name:'type',type:'string',desc:'种类编码'},{name:'qihao',type:'string',desc:'期号'},{name:'open_Code',type:'string',desc:'中奖号码'},{name:'date',type:'string',desc:'发布日期'}],
      example:'{"type":"ssq"}', response:'{"code":200,"msg":"success","data":{"type":"ssq","qihao":"2025124","open_Code":"01,02,18,19,21,33+13"}}' },

    { id:'nz_33', name:'二维码图生成', desc:'生成二维码图片。免费接口。', price:0, method:'POST', endpoint:'/api/nz/33',
      params:[{name:'url',type:'string',required:true,desc:'链接或文字'}],
      responseParams:[{name:'结果',type:'string',desc:'直接输出二维码'}],
      example:'{"url":"https://example.com"}', response:'直接输出' },

    { id:'nz_43', name:'DeepSeek-AI在线对话', desc:'DeepSeek-AI在线聊天对话接口。', price:0.01, method:'POST', endpoint:'/api/nz/43',
      params:[{name:'text',type:'string',required:true,desc:'对话内容'}],
      responseParams:[{name:'content',type:'string',desc:'AI答复内容'},{name:'code',type:'int',desc:'200=成功'}],
      example:'{"text":"你好"}', response:'{"code":200,"msg":"success","data":{"content":"你好！很高兴见到你。"}}' },

    { id:'nz_46', name:'代理http请求', desc:'爬虫代理请求，每日更新上百个IP代理。', price:0.002, method:'POST', endpoint:'/api/nz/46',
      params:[{name:'url',type:'string',required:true,desc:'网址'},{name:'ip',type:'string',required:false,desc:'模拟IP'},{name:'ua',type:'string',required:false,desc:'模拟UA'},{name:'refer',type:'string',required:false,desc:'来源地址'},{name:'cookie',type:'string',required:false,desc:'cookie'},{name:'header',type:'string',required:false,desc:'模拟头部'},{name:'get_cookie',type:'string',required:false,desc:'返回全部信息'}],
      responseParams:[{name:'body',type:'string',desc:'网站回调'},{name:'code',type:'int',desc:'HTTP响应状态码'}],
      example:'{"url":"https://example.com"}', response:'{"code":200,"msg":"success","data":{"body":"..."}}' },

    { id:'nz_3', name:'短视频祛水印', desc:'各类短视频(图集)水印祛除解析。', price:0.02, method:'POST', endpoint:'/api/nz/3',
      params:[{name:'url',type:'string',required:true,desc:'作品链接'}],
      responseParams:[{name:'type',type:'string',desc:'作品类型'},{name:'url',type:'string',desc:'作品链接'},{name:'video',type:'string',desc:'祛水印链接'},{name:'cover',type:'string',desc:'封面链接'},{name:'images',type:'array',desc:'图集数组'}],
      example:'{"url":"https://v.douyin.com/xxxx/"}', response:'{"code":200,"msg":"解析成功","data":{"type":"图集","url":"..."}}' },

    { id:'nz_55', name:'舔狗语录', desc:'随机一言-舔狗语录。免费接口。', price:0, method:'POST', endpoint:'/api/nz/55',
      params:[],
      responseParams:[{name:'text',type:'string',desc:'内容'},{name:'code',type:'int',desc:'200=成功'}],
      example:'{}', response:'{"code":200,"msg":"success","data":{"text":"..."}}' },

    { id:'nz_19', name:'二维码内容解析', desc:'二维码内容解析。免费接口。', price:0, method:'POST', endpoint:'/api/nz/19',
      params:[{name:'url',type:'string',required:true,desc:'jpg或png二维码链接'}],
      responseParams:[{name:'analysis',type:'string',desc:'识别内容'},{name:'code',type:'int',desc:'200=成功'}],
      example:'{"url":"https://example.com/qr.png"}', response:'{"code":200,"msg":"success","data":{"analysis":"https://baidu.com"}}' },

    { id:'nz_18', name:'随机一言', desc:'随机一段句子。免费接口。', price:0, method:'POST', endpoint:'/api/nz/18',
      params:[],
      responseParams:[{name:'text',type:'string',desc:'内容'},{name:'code',type:'int',desc:'200=成功'}],
      example:'{}', response:'{"code":200,"msg":"success","data":{"text":"..."}}' },

    { id:'nz_9', name:'高清风景壁纸', desc:'每日不重复的高清超美风景壁纸。免费接口。', price:0, method:'POST', endpoint:'/api/nz/9',
      params:[],
      responseParams:[{name:'结果',type:'string',desc:'直接输出壁纸'}],
      example:'{}', response:'直接输出' },

    { id:'nz_54', name:'邮件代发送', desc:'代发邮件API。', price:0.01, method:'POST', endpoint:'/api/nz/54',
      params:[{name:'mail',type:'string',required:true,desc:'收信邮箱'},{name:'title',type:'string',required:true,desc:'邮件标题'},{name:'text',type:'string',required:true,desc:'邮件内容'},{name:'lang',type:'string',required:false,desc:'语言，例如zh'}],
      responseParams:[{name:'mail',type:'string',desc:'收信邮箱'},{name:'title',type:'string',desc:'邮件标题'},{name:'text',type:'string',desc:'邮件内容'}],
      example:'{"mail":"test@test.com","title":"测试","text":"内容"}', response:'{"code":200,"msg":"发信成功","data":{}}' },

    // AI 对话
    { id:'ai_1', name:'DeepSeek 对话', desc:'DeepSeek AI 在线聊天', price:0.01, method:'POST', endpoint:'/api/nz/43', params:[{name:'text',type:'string',required:true,desc:'对话内容'}], example:'{"text":"你好"}' },
    { id:'ai_2', name:'智谱 GLM 对话', desc:'智谱 GLM 大模型对话', price:0.02, method:'POST', endpoint:'/api/zhipu/chat', params:[{name:'prompt',type:'string',required:true,desc:'对话内容'}], example:'{"prompt":"你好"}' },
    { id:'ai_3', name:'ModelScope 对话', desc:'ModelScope AI 对话', price:0.02, method:'POST', endpoint:'/api/modelscope/chat', params:[{name:'prompt',type:'string',required:true,desc:'对话内容'}], example:'{"prompt":"你好"}' }
  ],

  draw: [
    { id:'draw_1', name:'ModelScope 绘画', desc:'主力绘画，画质高，模型Tongyi-MAI/Z-Image-Turbo', price:0.05, method:'POST', endpoint:'/api/draw/modelscope',
      params:[{name:'prompt',type:'string',required:true,desc:'绘画提示词'}],
      responseParams:[{name:'url',type:'string',desc:'图片URL'}],
      example:'{"prompt":"一只猫"}', response:'{"url":"https://..."}' },

    { id:'draw_2', name:'智谱绘画', desc:'智谱BigModel cogview-3-flash', price:0.05, method:'POST', endpoint:'/api/draw/zhipu',
      params:[{name:'prompt',type:'string',required:true,desc:'绘画提示词'}],
      responseParams:[{name:'url',type:'string',desc:'图片URL'}],
      example:'{"prompt":"一只猫"}', response:'{"url":"https://..."}' },

    { id:'draw_3', name:'智谱视频', desc:'智谱cogvideox-flash视频生成', price:0.10, method:'POST', endpoint:'/api/draw/zhipu-video',
      params:[{name:'prompt',type:'string',required:true,desc:'视频提示词'}],
      responseParams:[{name:'url',type:'string',desc:'视频URL'}],
      example:'{"prompt":"一只猫在跑"}', response:'{"url":"https://..."}' },

    { id:'draw_4', name:'Cloudflare 绘画', desc:'Cloudflare Workers AI flux-1-schnell', price:0.03, method:'POST', endpoint:'/api/draw/cf',
      params:[{name:'prompt',type:'string',required:true,desc:'绘画提示词'}],
      responseParams:[{name:'url',type:'string',desc:'图片URL'}],
      example:'{"prompt":"一只猫"}', response:'{"url":"https://..."}' },

    { id:'draw_5', name:'Agnes 绘画', desc:'Agnes AI agnes-image-2.1-flash', price:0.04, method:'POST', endpoint:'/api/draw/agnes',
      params:[{name:'prompt',type:'string',required:true,desc:'绘画提示词'}],
      responseParams:[{name:'url',type:'string',desc:'图片URL'}],
      example:'{"prompt":"一只猫"}', response:'{"url":"https://..."}' },

    { id:'draw_6', name:'Agnes 改图', desc:'Agnes AI agnes-image-2.5-flash 改图', price:0.05, method:'POST', endpoint:'/api/draw/agnes-edit',
      params:[{name:'prompt',type:'string',required:true,desc:'修改提示词'},{name:'image_url',type:'string',required:true,desc:'原图地址'}],
      responseParams:[{name:'url',type:'string',desc:'新图URL'}],
      example:'{"prompt":"改成蓝色","image_url":"https://example.com/cat.jpg"}', response:'{"url":"https://..."}' }
  ],

  free: [],
  sms: []
};